import sys
import gcd
import powmod

#k is a element in the cycle generated by a
def orderOfACyclicElement(a,ordA,k):
    #ord a^k
    print(f"A / gcd(A,k)")
    print(f"order of {powmod.powMod(a,k,1,ordA+1)} = {ordA} / {gcd.gcd(ordA,k)} mod {ordA+1}")
    return ordA // gcd.gcd(ordA,k)

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: " + sys.argv[0] + " a orderA k, where you are finding order(a^k)")
        quit()
    print(orderOfACyclicElement(int(sys.argv[1]),int(sys.argv[2]),int(sys.argv[3])))